"""IATA airport code → city/airport name lookup."""

AIRPORTS = {
    # United Kingdom & Ireland
    "BRS": "Bristol",
    "LTN": "London Luton",
    "STN": "London Stansted",
    "LGW": "London Gatwick",
    "LHR": "London Heathrow",
    "LCY": "London City",
    "MAN": "Manchester",
    "BHX": "Birmingham",
    "EDI": "Edinburgh",
    "GLA": "Glasgow",
    "BFS": "Belfast",
    "LPL": "Liverpool",
    "NCL": "Newcastle",
    "EMA": "East Midlands",
    "ABZ": "Aberdeen",
    "CWL": "Cardiff",
    "SOU": "Southampton",
    "BOH": "Bournemouth",
    "EXT": "Exeter",
    "NQY": "Newquay",
    "DSA": "Doncaster",
    "LBA": "Leeds Bradford",
    "PIK": "Glasgow Prestwick",
    "SNN": "Shannon",
    "DUB": "Dublin",
    "ORK": "Cork",
    "KNO": "Knock",
    # Spain
    "BCN": "Barcelona",
    "AGP": "Malaga",
    "ALC": "Alicante",
    "PMI": "Palma de Mallorca",
    "TFS": "Tenerife South",
    "TFN": "Tenerife North",
    "LPA": "Gran Canaria",
    "ACE": "Lanzarote",
    "FUE": "Fuerteventura",
    "IBZ": "Ibiza",
    "MAD": "Madrid",
    "VLC": "Valencia",
    "SVQ": "Seville",
    "GRO": "Girona",
    "REU": "Reus",
    "BIO": "Bilbao",
    "SCQ": "Santiago de Compostela",
    "MAH": "Menorca",
    "MJV": "Murcia",
    "ZAZ": "Zaragoza",
    # Italy
    "FCO": "Rome Fiumicino",
    "CIA": "Rome Ciampino",
    "MXP": "Milan Malpensa",
    "BGY": "Milan Bergamo",
    "NAP": "Naples",
    "VCE": "Venice",
    "TSF": "Venice Treviso",
    "BLQ": "Bologna",
    "PSA": "Pisa",
    "CTA": "Catania",
    "PMO": "Palermo",
    "BRI": "Bari",
    "TRN": "Turin",
    "SUF": "Lamezia Terme",
    "CRV": "Crotone",
    "CAG": "Cagliari",
    "AHO": "Alghero",
    "OLB": "Olbia",
    "TRS": "Trieste",
    "VRN": "Verona",
    "GOA": "Genoa",
    "PEG": "Perugia",
    # France
    "CDG": "Paris CDG",
    "ORY": "Paris Orly",
    "BVA": "Paris Beauvais",
    "NCE": "Nice",
    "MRS": "Marseille",
    "LYS": "Lyon",
    "TLS": "Toulouse",
    "BOD": "Bordeaux",
    "NTE": "Nantes",
    # Germany
    "BER": "Berlin",
    "SXF": "Berlin Schönefeld",
    "FRA": "Frankfurt",
    "HHN": "Frankfurt Hahn",
    "MUC": "Munich",
    "CGN": "Cologne",
    "HAM": "Hamburg",
    "DUS": "Düsseldorf",
    "STR": "Stuttgart",
    "DTM": "Dortmund",
    # Portugal
    "LIS": "Lisbon",
    "OPO": "Porto",
    "FAO": "Faro",
    "FNC": "Funchal",
    "PDL": "Ponta Delgada",
    # Greece
    "ATH": "Athens",
    "SKG": "Thessaloniki",
    "HER": "Heraklion",
    "CHQ": "Chania",
    "RHO": "Rhodes",
    "CFU": "Corfu",
    "KGS": "Kos",
    "JTR": "Santorini",
    "JMK": "Mykonos",
    "ZTH": "Zakynthos",
    "KLX": "Kalamata",
    "EFL": "Kefalonia",
    "PVK": "Preveza",
    # Turkey
    "IST": "Istanbul",
    "SAW": "Istanbul Sabiha",
    "AYT": "Antalya",
    "DLM": "Dalaman",
    "BJV": "Bodrum",
    "ADB": "Izmir",
    # Poland
    "WAW": "Warsaw",
    "WMI": "Warsaw Modlin",
    "KRK": "Krakow",
    "GDN": "Gdansk",
    "WRO": "Wroclaw",
    "KTW": "Katowice",
    "POZ": "Poznan",
    "LUZ": "Lublin",
    "RZE": "Rzeszow",
    "SZZ": "Szczecin",
    "BZG": "Bydgoszcz",
    # Hungary
    "BUD": "Budapest",
    "DEB": "Debrecen",
    # Romania
    "OTP": "Bucharest",
    "CLJ": "Cluj-Napoca",
    "TSR": "Timisoara",
    "IAS": "Iasi",
    "SBZ": "Sibiu",
    "CRA": "Craiova",
    "SUJ": "Satu Mare",
    "BCM": "Bacau",
    # Bulgaria
    "SOF": "Sofia",
    "BOJ": "Burgas",
    "VAR": "Varna",
    # Czech Republic
    "PRG": "Prague",
    "BRQ": "Brno",
    # Austria
    "VIE": "Vienna",
    "SZG": "Salzburg",
    # Switzerland
    "GVA": "Geneva",
    "ZRH": "Zurich",
    "BSL": "Basel",
    # Netherlands
    "AMS": "Amsterdam",
    "EIN": "Eindhoven",
    # Belgium
    "BRU": "Brussels",
    "CRL": "Brussels Charleroi",
    # Nordic
    "CPH": "Copenhagen",
    "OSL": "Oslo",
    "TRF": "Oslo Torp",
    "ARN": "Stockholm",
    "NYO": "Stockholm Skavsta",
    "GOT": "Gothenburg",
    "HEL": "Helsinki",
    # Baltic
    "RIX": "Riga",
    "VNO": "Vilnius",
    "KUN": "Kaunas",
    "TLL": "Tallinn",
    # Croatia
    "ZAG": "Zagreb",
    "DBV": "Dubrovnik",
    "SPU": "Split",
    "PUY": "Pula",
    "ZAD": "Zadar",
    # Other Balkans
    "BEG": "Belgrade",
    "SJJ": "Sarajevo",
    "TGD": "Podgorica",
    "TIV": "Tivat",
    "SKP": "Skopje",
    "TIA": "Tirana",
    "PRN": "Pristina",
    # Cyprus
    "LCA": "Larnaca",
    "PFO": "Paphos",
    # Israel
    "TLV": "Tel Aviv",
    # Morocco
    "RAK": "Marrakech",
    "CMN": "Casablanca",
    "FEZ": "Fez",
    "AGA": "Agadir",
    # Malta
    "MLA": "Malta",
    # Iceland
    "KEF": "Reykjavik",
    # Egypt
    "HRG": "Hurghada",
    "SSH": "Sharm el-Sheikh",
    # Tunisia
    "TUN": "Tunis",
    "NBE": "Enfidha",
    # Other
    "GIB": "Gibraltar",
    "JER": "Jersey",
    "GCI": "Guernsey",
    "IOM": "Isle of Man",
}


def airport_name(iata: str) -> str:
    """Return 'City Name (CODE)' or just 'CODE' if unknown."""
    name = AIRPORTS.get(iata.upper())
    if name:
        return f"{name} ({iata.upper()})"
    return iata.upper()
